### ISSUE TITLE
valid bids get refunded

### ISSUE THREAD

**Issue by bitcoiners** [MattyIce/postpromoter#29]
Saw something strange today. A bunch of valid bids got refunded, all at the same time. Unfortunately I did not keep the log, so not sure what happened. 

```
pushup transfer 1 SBD to funatoz Bid refund: - Invalid post URL in memo.
1 hour ago
f7b45f5bPushup
pushup transfer 3 SBD to baldos Bid refund: - Invalid post URL in memo.
1 hour ago
d79765a7Pushup
pushup transfer 1.200 SBD to arslanhyder Bid refund: - Invalid post URL in memo.
1 hour ago
0828a443Pushup
pushup transfer 1 SBD to alejandr Bid refund: - Invalid post URL in memo.
1 hour ago
be369d88Pushup
pushup transfer 1 SBD to termitemusic Bid refund: - Invalid post URL in memo.
1 hour ago
05264947Pushup
pushup transfer 1 SBD to dirkboy41 Bid refund: - Invalid post URL in memo.
1 hour ago
60c99ba2Pushup
pushup transfer 1 STEEM to cryptoplayer Bid refund: - Invalid post URL in memo.
1 hour ago
0a4b6557Pushup
pushup transfer 2 SBD to gringalicious Bid refund: - Invalid post URL in memo.
1 hour ago
105e019dPushup
pushup transfer 1 SBD to bapin Bid refund: - Invalid post URL in memo.
1 hour ago
2f518ac2Pushup
pushup transfer 1 SBD to faces Bid refund: - Invalid post URL in memo.

```

**Comment by SuggeElson** [comment]
Pretty much same to me but without refund because of error.

4|upme     | Sat Jan 20 2018 03:59:19 GMT+0200 (EET) - Error sending refund to @winphotographers for: 2.6 SBD, Error: Error: HTTP 503: Service Temporarily Unavailable
4|upme     | Sat Jan 20 2018 03:59:19 GMT+0200 (EET) - Error sending refund to @moliyana for: 2.65 SBD, Error: Error: HTTP 503: Service Temporarily Unavailable
4|upme     | Sat Jan 20 2018 03:59:19 GMT+0200 (EET) - Error sending refund to @moliyana for: 2.65 SBD, Error: Error: HTTP 503: Service Temporarily Unavailable
4|upme     | Sat Jan 20 2018 03:59:19 GMT+0200 (EET) - Error sending refund to @ronahmad for: 2.5 SBD, Error: Error: HTTP 503: Service Temporarily Unavailable
4|upme     | Sat Jan 20 2018 03:59:19 GMT+0200 (EET) - Error sending refund to @pramodbarmunda for: 2.501 SBD, Error: Error: HTTP 503: Service Temporarily Unavailable
4|upme     | Sat Jan 20 2018 03:59:19 GMT+0200 (EET) - Error sending refund to @fakhrizal for: 2.6 SBD, Error: Error: HTTP 503: Service Temporarily Unavailable
4|upme     | Sat Jan 20 2018 03:59:19 GMT+0200 (EET) - Error sending refund to @ohicklin for: 2.5 SBD, Error: Error: HTTP 503: Service Temporarily Unavailable
4|upme     | Sat Jan 20 2018 03:59:19 GMT+0200 (EET) - Error sending refund to @fakhrizal for: 2.6 SBD, Error: Error: HTTP 503: Service Temporarily Unavailable

**Comment by MattyIce** [comment]
@bitcoiners and @SuggeElson these issues are due to the RPC node going down. I have just pushed a change to allow automatic failover to the next node on the list if these issues occur. It is not fully tested yet, you can read more about it in this issue: [https://github.com/MattyIce/postpromoter/issues/28](https://github.com/MattyIce/postpromoter/issues/28)
