### ISSUE TITLE
Multiple blacklist donations in short time trigger mayhem

### ISSUE THREAD

**Issue by themarkymark-steem** [MattyIce/postpromoter#38]
I had 5 incoming bids that were on a blacklist, and sending them to donation account caused the bot to start failing very rapidly and failing over nodes.  

It appears it is trigging duplication transaction errors.   Something that seems to happen when a single user sends multiple bids for the same amount to different posts in a very short period of time.

I thought this error was limited to Jussi but none of the nodes selected are Jussi nodes.

**Comment by SuggeElson** [comment]
Maybe some delay 2-3 sec between refunds is a good idea.

**Comment by themarkymark-steem** [comment]
Not sure if it even has to be that long but would require testing. 

I think pending refunds should be wrapped up before transfer funds even happens.

**Comment by MattyIce** [comment]
I made a couple of changes to help handle this situation better:

1. assert_exceptions no longer "count" as far as node failover is concerned. This way these type of errors will no longer trigger failover to a new node since it's not an issue with the node in the first place.

2. I changed the retry time for refund transactions to be randomly chosen between 3 and 12 seconds. This way if a bunch of the same refunds try to go out at the same time, they may still get a duplicate transaction exception, but they will retry at different times making them much more likely to go through. I tried this a couple times in testing and all of the refunds went through with only a few errors.
