### ISSUE TITLE
Issue deploying on Heroku

### ISSUE THREAD

**Issue by hugeprestigellc** [MattyIce/postpromoter#51]
I'm following the very simple instructions on how to deploy a node js app to Heroku, from this page: https://devcenter.heroku.com/articles/deploying-nodejs

I can run the app locally with "heroku local web" and everything else appears to go smoothly. But when I finally try to deploy the app to Heroku with this command: git push heroku master

I get the following error:

remote: !	The requested API endpoint was not found. Are you using the right HTTP verb (i.e. `GET` vs. `POST`), and did you specify your intended version with the `Accept` header?
remote: 
To ...
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to ...

Any thoughts?

**Comment by MattyIce** [comment]
Sorry @hugeprestigellc I'm not at all familiar with heroku so can't help you here. Did you try googling the issue?

**Comment by hitwill** [comment]
@hugeprestigellc I had some problems but resolved them as follows:
1. Run heroku update to make sure your CLI is up to date
2. Heroku has a dynamic listening port, so you will need to update post promotor.js by adding the line below:
![image](https://user-images.githubusercontent.com/2501079/37314278-53310d16-26a7-11e8-80ae-323cbe9874de.png)
3. You probably have two git folders (one for postpromotor) and one in your root folder, which is linked to your heroku account. You will need to delete the postpromotor git folder unfortunately because of the code change.
4. Make sure the package.json dependencies in the postpromotor folder are copied to those in your root folder for heroku.
5. Add node_modules to git ignore in your root folder
6. Run NPM install

You should be able to push to heroku now. If necessary. Let me know how it goes

**Comment by MattyIce** [comment]
@hugeprestigellc @hitwill this was just fixed in a PR by @chhantyal which is now merged in. Closing this task but please let me know if there are any other issues deploying on heroku.
